$SEC Data
"Acquisition Started: |DDDDDDDDD |TTTTTTTTTT" ASTIME ASTIME
$SETE #IV1 1
$SETE #IV2 2
$SETE #IV3 3
$SETE #IV4 4
$SETE #IV5 5
$SETE #IV6 6
$SETE #IV7 7
$SETE #IV8 8
"Live time: |FFFFFFFF" ELIVE
"Real Time: |FFFFFFFF" EREAL
$SETE #IV9 48
$BT CHANNELS
$SETS #IV9 1
$IFNOT #IV9
$SETE #IV9 54
$ENDIF
"|IIII:|IIIIII |IIIIII |IIIIII |IIIIII |IIIIII |IIIIII |IIIIII |IIIIII" #IV1 SPECDATA(#IV1) SPECDATA(#IV2) SPECDATA(#IV3) SPECDATA(#IV4) SPECDATA(#IV5) SPECDATA(#IV6) SPECDATA(#IV7) SPECDATA(#IV8)
$SETA #IV1 8
$SETA #IV2 8
$SETA #IV3 8
$SETA #IV4 8
$SETA #IV5 8
$SETA #IV6 8
$SETA #IV7 8
$SETA #IV8 8
$ET 8


